language: r

warnings_are_errors: true

sudo: required

os:
  - linux
#  - osx

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

apt_packages:
  - python-numpy
